# Generated by Django 3.2.7 on 2021-10-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
